### ISSUE TITLE
gb-link.h is missing

### ISSUE THREAD

**Issue by Edman274** [Dhole/gb-link-stm32f411#1]
When trying to build, I get the following:

~/git/gb-link-stm32f411/src$ make
gb-link.c:10:10: fatal error: gb-link.h: No such file or directory
   10 | #include "gb-link.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [../rules.mk:199: gb-link.o] Error 1

**Comment by Dhole** [comment]
Sorry, I forgot to check out this header file.  I've added it in 449c5cc7eb4008589f2c8a7e9b8311930cc19cec

**Comment by Edman274** [comment]
Is there something I'm missing when I do a make now and get just the following error: 

gb-link.c:24:3: error: 'const struct rcc_clock_scale' has no member named 'power_save'
   24 |  .power_save = 1,
      |   ^~~~~~~~~~
gb-link.c: In function 'clock_setup':
gb-link.c:35:2: warning: 'rcc_clock_setup_hse_3v3' is deprecated: Use rcc_clock_setup_pll as direct replacement [-Wdeprecated-declarations]
   35 |  rcc_clock_setup_hse_3v3(&rcc_hse_8mhz_3v3_96mhz);
      |  ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/sam/git/libopencm3//include/libopencm3/stm32/rcc.h:32,
                 from gb-link.c:1:
/home/sam/git/libopencm3//include/libopencm3/stm32/f4/rcc.h:1101:83: note: declared here
 1101 | eprecated("Use rcc_clock_setup_pll as direct replacement"))) rcc_clock_setup_hse_3v3(const struct rcc_clock_scale *clock);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~

make: *** [../rules.mk:199: gb-link.o] Error 1

**Comment by Edman274** [comment]
I apologize if I'm missing anything helpful in raising this issue; I've never tried to meaningfully build from source with third party libraries installed outside of a package manager. I'm using the latest git version of libopencm3 which I'm assuming are raising those warning messages, but I don't know if the header file is out of sync with the implementation, and if / whether I should just edit this on my own end.

**Comment by Dhole** [comment]
Ah, probably this issue is arising due to changes in recent versions of libopencm3.  It successfully builds for me with https://github.com/libopencm3/libopencm3 at commit `b76d853a723d39bbc083495bb7460cf3f071476c`.
So following these steps should make it compile:
```sh
cd ~/git
git clone https://github.com/libopencm3/libopencm3
cd libopencm3
git checkout b76d853a723d39bbc083495bb7460cf3f071476c
```

Let me know if this works for you!

**Comment by Edman274** [comment]
Hey! Really sorry about the delay - because I wasn't able to solder the cable together, I put testing this out on hold, and am now revisiting it after having set up this janky thing: 
![IMG_20200814_001150](https://user-images.githubusercontent.com/3466697/90213309-759ff580-ddc3-11ea-9f67-d7cb9de81eaa.jpg)

As far as I could tell, updating the project to be compatible with the latest revision of libopenocm3 was just commenting out the LDSCRIPT declaration, including a DEVICE declaration, removing a power_save assignment, and calling the function rcc_clock_setup_pll. That's what I tried to do on my local, and I was able to get it to successfully compile.

What I don't know how to do at this point is actually write the generated output to the board. I would expect 'st-flash write gb-link.bin 0x8000000' (where gb-link.bin was generated from arm-none-eabi-objcopy -O binary gb-link.elf gb-link.bin) to be correct, but I'm new to this, and upon writing that out to the board, I end up with the board saying that there's no SRAM, no flash, and the chip ID is 0000. From compiling the ELF, what happens then?

**Comment by Edman274** [comment]
Okay, I figured out what's going on. The reason that I tried to build from the latest revision in libopencm3 is that I was getting errors associated with missing header files when I did the checkout of the old revision of that library. But I neglected to do a make clean / make after checking out `b76d853a723d39bbc083495bb7460cf3f071476c` , which would've prevented that error. Once I did a checkout of that revision again, a `make clean`, and reverted my local copy to match your revision, I can sniff, but not write out to a file:

`sam@sam-VirtualBox:~/git/gb-link-host/target/debug$ ./gb-link -m print --file ~/cool_dude.jpg --serial /dev/ttyACM1
Development board is: St
Using serial device: /dev/ttyACM1 at baud rate: 1000000

Resetting board using st-flash utility...
2020-08-14T01:03:17 INFO common.c: Loading device parameters....
2020-08-14T01:03:17 INFO common.c: Device connected is: F4 device (low power) - stm32f411re, id 0x10006431
2020-08-14T01:03:17 INFO common.c: SRAM size: 0x20000 bytes (128 KiB), Flash: 0x80000 bytes (512 KiB) in pages of 16384 bytes

Connected!
Setting Print mode
Error opening image at file "/home/sam/cool_dude.jpg": IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

I now know for a fact that I can sniff traffic from the GameBoy Camera - everything is working except for writing out a file. I potentially don't even have an issue with this since I can just `cat` out the result to a file from sniff and then parse that myself - but is there anything weird about my arguments to the host program?

(As an aside, I can't thank you enough for actually taking the time to both write this all out and release it on an open source platform.)

**Comment by Dhole** [comment]
> Hey! Really sorry about the delay - because I wasn't able to solder the cable together, I put testing this out on hold, and am now revisiting it after having set up this janky thing:
It's really cool to see other people doing the hardware setup to run this project :)

It seems you managed to run the firmware properly and everything is working as expected on the microcontroller side!

> `sam@sam-VirtualBox:~/git/gb-link-host/target/debug$ ./gb-link -m print --file ~/cool_dude.jpg --serial /dev/ttyACM1
> Development board is: St
> Using serial device: /dev/ttyACM1 at baud rate: 1000000
> 
> Resetting board using st-flash utility...
> 2020-08-14T01:03:17 INFO common.c: Loading device parameters....
> 2020-08-14T01:03:17 INFO common.c: Device connected is: F4 device (low power) - stm32f411re, id 0x10006431
> 2020-08-14T01:03:17 INFO common.c: SRAM size: 0x20000 bytes (128 KiB), Flash: 0x80000 bytes (512 KiB) in pages of 16384 bytes
> 
> Connected!
> Setting Print mode
> Error opening image at file "/home/sam/cool_dude.jpg": IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })`
> 
> I now know for a fact that I can sniff traffic from the GameBoy Camera - everything is working except for writing out a file. I potentially don't even have an issue with this since I can just `cat` out the result to a file from sniff and then parse that myself - but is there anything weird about my arguments to the host program?

I've checked the source code of `gb-link-host` to refresh my mind and I believe I found the problem you're encountering.  Probably the issue was regarding the documentation of `gb-link-host`.  The program has 3 modes of operation: sniff, printer, print.
**print** is the mode used to print the image given by the `--file` argument in the gameboy printer.  In this mode you connect the microcontroller to the gameboy printer.
**printer** is the mode used to act as a virtual printer and receive pictures from the gameboy.  In this mode you connect the microcontroller to the gameboy.

So what you want to do is use `-m printer`, without a `--file` argument.  The program will create a new file called `gb_printer_TIMESTAMP.png` where `TIMESTAMP` is the current time.

**Comment by Dhole** [comment]
> (As an aside, I can't thank you enough for actually taking the time to both write this all out and release it on an open source platform.)

Thanks for the kind words!  It's really nice from my side to see people replicating the hardware setup to run this :)

**Comment by Edman274** [comment]
Is it the case that the cable has to be setup a different way to have the **printer** command work? I'm guessing that for printer, we'd want to have the microcontroller plugged directly into the gameboy without a parallel connection to the real printer, right? With a GB to printer connection and a parallel connection to the microcontroller, a `Print Error 02` gets returned, but that doesn't seem surprising to me, since I'm guessing that both the microcontroller and the printer are attempting to return data to the GB and that causes a conflict.

In the meantime, I was able to just update the gb-link-host program with a trivial change to how we print out data in sniff (print underscores when receiving zeroes because it could either be "no data" or it could be zeroes), `cat` that into a file, and then read the file and output the image in Python: https://gist.github.com/Edman274/4360226fe8ffe008e05cf3a31ff26e32 

I'll try it the way that you described later today and give you an update but I wanted to let you know that as far as just getting the data digitized and backed up, that's working for me. Thanks again!

**Comment by Dhole** [comment]
> Is it the case that the cable has to be setup a different way to have the **printer** command work? I'm guessing that for printer, we'd want to have the microcontroller plugged directly into the gameboy without a parallel connection to the real printer, right? With a GB to printer connection and a parallel connection to the microcontroller, a `Print Error 02` gets returned, but that doesn't seem surprising to me, since I'm guessing that both the microcontroller and the printer are attempting to return data to the GB and that causes a conflict.

Exactly, for the **printer** command you'd want the microcontroller plugged directly into the gameboy, without a parallel connection to the real printer.  This is because the microcontroller will be acting as a virtual printer and responding to the gameboy.

> In the meantime, I was able to just update the gb-link-host program with a trivial change to how we print out data in sniff (print underscores when receiving zeroes because it could either be "no data" or it could be zeroes), cat that into a file, and then read the file and output the image in Python: https://gist.github.com/Edman274/4360226fe8ffe008e05cf3a31ff26e32

cool!
